services:
  - type: web
    name: autocatalog
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: autocatalog-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1